// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2026_manajemenruang_backend.Data;

#nullable disable

namespace _2026_manajemenruang_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260214044632_AddPeminjamanTable")]
    partial class AddPeminjamanTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("_2026_manajemenruang_backend.Models.Peminjaman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Keterangan")
                        .HasColumnType("longtext");

                    b.Property<string>("NamaPeminjam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RuanganId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TanggalPinjam")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("TanggalSelesai")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RuanganId");

                    b.ToTable("Peminjaman");
                });

            modelBuilder.Entity("_2026_manajemenruang_backend.Models.Ruangan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Gedung")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Kapasitas")
                        .HasColumnType("int");

                    b.Property<string>("NamaRuangan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Ruangans");
                });

            modelBuilder.Entity("_2026_manajemenruang_backend.Models.Peminjaman", b =>
                {
                    b.HasOne("_2026_manajemenruang_backend.Models.Ruangan", "Ruangan")
                        .WithMany()
                        .HasForeignKey("RuanganId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ruangan");
                });
#pragma warning restore 612, 618
        }
    }
}
